// <auto-generated />
using System;
using DMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DMSContext))]
    [Migration("20260208163118_ExpandEntities")]
    partial class ExpandEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DMS.Domain.Entities.BinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TacGiaId")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThongBaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TacGiaId");

                    b.HasIndex("ThongBaoId");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("DMS.Domain.Entities.ChuyenMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuyenMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ChuyenMucs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MauSac = "blue",
                            TenChuyenMuc = "News"
                        },
                        new
                        {
                            Id = 2,
                            MauSac = "orange",
                            TenChuyenMuc = "Policy"
                        });
                });

            modelBuilder.Entity("DMS.Domain.Entities.CuocTroChuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("LaNhom")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenCuocTroChuyen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CuocTroChuyens");
                });

            modelBuilder.Entity("DMS.Domain.Entities.LoaiTaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LoaiTaiLieus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Tài liệu Portable Document Format",
                            TenLoai = "PDF"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Tài liệu Microsoft Word",
                            TenLoai = "DOCX"
                        });
                });

            modelBuilder.Entity("DMS.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhongBanId");

                    b.HasIndex("VaiTroId");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@company.com",
                            HoTen = "Administrator",
                            MatKhau = "admin123",
                            NgayTao = new DateTime(2026, 2, 8, 23, 31, 18, 641, DateTimeKind.Local).AddTicks(3828),
                            PhongBanId = 1,
                            TrangThai = "Active",
                            VaiTroId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "a.nguyen@company.com",
                            HoTen = "Nguyen Van A",
                            MatKhau = "user123",
                            NgayTao = new DateTime(2026, 2, 8, 23, 31, 18, 641, DateTimeKind.Local).AddTicks(3844),
                            PhongBanId = 2,
                            TrangThai = "Active",
                            VaiTroId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "b.tran@company.com",
                            HoTen = "Tran Thi B",
                            MatKhau = "user123",
                            NgayTao = new DateTime(2026, 2, 8, 23, 31, 18, 641, DateTimeKind.Local).AddTicks(3846),
                            PhongBanId = 3,
                            TrangThai = "Active",
                            VaiTroId = 2
                        });
                });

            modelBuilder.Entity("DMS.Domain.Entities.NhatKyHoatDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoiTuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NhatKyHoatDongs");
                });

            modelBuilder.Entity("DMS.Domain.Entities.PhienBanTaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChuThayDoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("SoPhienBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaiLieuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("TaiLieuId");

                    b.ToTable("PhienBanTaiLieus");
                });

            modelBuilder.Entity("DMS.Domain.Entities.PhongBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PhongBans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Phòng Công nghệ thông tin",
                            TenPhongBan = "IT"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Phòng Tài chính",
                            TenPhongBan = "Finance"
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "Phòng Nhân sự",
                            TenPhongBan = "HR"
                        });
                });

            modelBuilder.Entity("DMS.Domain.Entities.TaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuSoHuuId")
                        .HasColumnType("int");

                    b.Property<string>("DungLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiTaiLieuId")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongBanId")
                        .HasColumnType("int");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChuSoHuuId");

                    b.HasIndex("LoaiTaiLieuId");

                    b.HasIndex("PhongBanId");

                    b.ToTable("TaiLieus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChuSoHuuId = 1,
                            DungLuong = "2.5 MB",
                            LoaiTaiLieuId = 1,
                            MoTa = "Finalized financial report for Q3 2025.",
                            NgayTao = new DateTime(2026, 2, 8, 23, 31, 18, 641, DateTimeKind.Local).AddTicks(3873),
                            PhongBanId = 2,
                            TenTaiLieu = "Q3_Financial_Internal.pdf",
                            TrangThai = "Published"
                        },
                        new
                        {
                            Id = 2,
                            ChuSoHuuId = 3,
                            DungLuong = "1.2 MB",
                            LoaiTaiLieuId = 2,
                            MoTa = "Working draft for handbook update.",
                            NgayTao = new DateTime(2026, 2, 8, 23, 31, 18, 641, DateTimeKind.Local).AddTicks(3877),
                            PhongBanId = 3,
                            TenTaiLieu = "Employee_Handbook_Draft.docx",
                            TrangThai = "Draft"
                        });
                });

            modelBuilder.Entity("DMS.Domain.Entities.ThanhVienCuocTroChuyen", b =>
                {
                    b.Property<int>("CuocTroChuyenId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2");

                    b.HasKey("CuocTroChuyenId", "NguoiDungId");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThanhVienCuocTroChuyens");
                });

            modelBuilder.Entity("DMS.Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuyenMucId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TacGiaId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenMucId");

                    b.HasIndex("TacGiaId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("DMS.Domain.Entities.TinNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuocTroChuyenId")
                        .HasColumnType("int");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiGuiId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CuocTroChuyenId");

                    b.HasIndex("NguoiGuiId");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("DMS.Domain.Entities.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VaiTros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Quản trị hệ thống",
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Người dùng thông thường",
                            TenVaiTro = "User"
                        });
                });

            modelBuilder.Entity("DMS.Domain.Entities.BinhLuan", b =>
                {
                    b.HasOne("DMS.Domain.Entities.NguoiDung", "TacGia")
                        .WithMany()
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DMS.Domain.Entities.ThongBao", "ThongBao")
                        .WithMany("DanhSachBinhLuan")
                        .HasForeignKey("ThongBaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TacGia");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("DMS.Domain.Entities.NguoiDung", b =>
                {
                    b.HasOne("DMS.Domain.Entities.PhongBan", "PhongBan")
                        .WithMany("DanhSachNguoiDung")
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DMS.Domain.Entities.VaiTro", "VaiTro")
                        .WithMany()
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongBan");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("DMS.Domain.Entities.NhatKyHoatDong", b =>
                {
                    b.HasOne("DMS.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DMS.Domain.Entities.PhienBanTaiLieu", b =>
                {
                    b.HasOne("DMS.Domain.Entities.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DMS.Domain.Entities.TaiLieu", "TaiLieu")
                        .WithMany("DanhSachPhienBan")
                        .HasForeignKey("TaiLieuId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiTao");

                    b.Navigation("TaiLieu");
                });

            modelBuilder.Entity("DMS.Domain.Entities.TaiLieu", b =>
                {
                    b.HasOne("DMS.Domain.Entities.NguoiDung", "ChuSoHuu")
                        .WithMany()
                        .HasForeignKey("ChuSoHuuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Domain.Entities.LoaiTaiLieu", "LoaiTaiLieu")
                        .WithMany()
                        .HasForeignKey("LoaiTaiLieuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Domain.Entities.PhongBan", "PhongBan")
                        .WithMany()
                        .HasForeignKey("PhongBanId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChuSoHuu");

                    b.Navigation("LoaiTaiLieu");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("DMS.Domain.Entities.ThanhVienCuocTroChuyen", b =>
                {
                    b.HasOne("DMS.Domain.Entities.CuocTroChuyen", "CuocTroChuyen")
                        .WithMany("DanhSachThanhVien")
                        .HasForeignKey("CuocTroChuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuocTroChuyen");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("DMS.Domain.Entities.ThongBao", b =>
                {
                    b.HasOne("DMS.Domain.Entities.ChuyenMuc", "ChuyenMuc")
                        .WithMany()
                        .HasForeignKey("ChuyenMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Domain.Entities.NguoiDung", "TacGia")
                        .WithMany()
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChuyenMuc");

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("DMS.Domain.Entities.TinNhan", b =>
                {
                    b.HasOne("DMS.Domain.Entities.CuocTroChuyen", "CuocTroChuyen")
                        .WithMany("DanhSachTinNhan")
                        .HasForeignKey("CuocTroChuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Domain.Entities.NguoiDung", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CuocTroChuyen");

                    b.Navigation("NguoiGui");
                });

            modelBuilder.Entity("DMS.Domain.Entities.CuocTroChuyen", b =>
                {
                    b.Navigation("DanhSachThanhVien");

                    b.Navigation("DanhSachTinNhan");
                });

            modelBuilder.Entity("DMS.Domain.Entities.PhongBan", b =>
                {
                    b.Navigation("DanhSachNguoiDung");
                });

            modelBuilder.Entity("DMS.Domain.Entities.TaiLieu", b =>
                {
                    b.Navigation("DanhSachPhienBan");
                });

            modelBuilder.Entity("DMS.Domain.Entities.ThongBao", b =>
                {
                    b.Navigation("DanhSachBinhLuan");
                });
#pragma warning restore 612, 618
        }
    }
}
