// <auto-generated />
using System;
using DMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DMS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(DMSContext))]
    [Migration("20260208141714_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DMS.Domain.Entities.BinhLuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TacGiaId")
                        .HasColumnType("int");

                    b.Property<string>("ThoiGian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThongBaoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TacGiaId");

                    b.HasIndex("ThongBaoId");

                    b.ToTable("BinhLuans");
                });

            modelBuilder.Entity("DMS.Domain.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@company.com",
                            HoTen = "Administrator",
                            MatKhau = "admin123",
                            PhongBan = "IT",
                            TrangThai = "active",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "a.nguyen@company.com",
                            HoTen = "Nguyen Van A",
                            MatKhau = "user123",
                            PhongBan = "Finance",
                            TrangThai = "active",
                            VaiTro = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "b.tran@company.com",
                            HoTen = "Tran Thi B",
                            MatKhau = "user123",
                            PhongBan = "HR",
                            TrangThai = "active",
                            VaiTro = "User"
                        });
                });

            modelBuilder.Entity("DMS.Domain.Entities.TaiLieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChuSoHuuId")
                        .HasColumnType("int");

                    b.Property<string>("DungLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhienBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChuSoHuuId");

                    b.ToTable("TaiLieus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChuSoHuuId = 1,
                            DungLuong = "2.5 MB",
                            Loai = "PDF",
                            MoTa = "Finalized financial report for Q3 2025.",
                            NgayTao = new DateTime(2026, 2, 8, 21, 17, 14, 43, DateTimeKind.Local).AddTicks(5053),
                            PhienBan = "v2.1",
                            PhongBan = "Finance",
                            TenTaiLieu = "Q3_Financial_Internal.pdf",
                            TrangThai = "Published"
                        },
                        new
                        {
                            Id = 2,
                            ChuSoHuuId = 3,
                            DungLuong = "1.2 MB",
                            Loai = "DOCX",
                            MoTa = "Working draft for handbook update.",
                            NgayTao = new DateTime(2026, 2, 8, 21, 17, 14, 43, DateTimeKind.Local).AddTicks(5071),
                            PhienBan = "v0.8",
                            PhongBan = "HR",
                            TenTaiLieu = "Employee_Handbook_Draft.docx",
                            TrangThai = "Draft"
                        });
                });

            modelBuilder.Entity("DMS.Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TacGiaId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TacGiaId");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("DMS.Domain.Entities.TinNhan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("LaTinNhanNhom")
                        .HasColumnType("bit");

                    b.Property<int>("NguoiGuiId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiNhanId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiGuiId");

                    b.HasIndex("NguoiNhanId");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("DMS.Domain.Entities.BinhLuan", b =>
                {
                    b.HasOne("DMS.Domain.Entities.NguoiDung", "TacGia")
                        .WithMany()
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DMS.Domain.Entities.ThongBao", "ThongBao")
                        .WithMany("DanhSachBinhLuan")
                        .HasForeignKey("ThongBaoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TacGia");

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("DMS.Domain.Entities.TaiLieu", b =>
                {
                    b.HasOne("DMS.Domain.Entities.NguoiDung", "ChuSoHuu")
                        .WithMany()
                        .HasForeignKey("ChuSoHuuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuSoHuu");
                });

            modelBuilder.Entity("DMS.Domain.Entities.ThongBao", b =>
                {
                    b.HasOne("DMS.Domain.Entities.NguoiDung", "TacGia")
                        .WithMany()
                        .HasForeignKey("TacGiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TacGia");
                });

            modelBuilder.Entity("DMS.Domain.Entities.TinNhan", b =>
                {
                    b.HasOne("DMS.Domain.Entities.NguoiDung", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DMS.Domain.Entities.NguoiDung", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanId");

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("DMS.Domain.Entities.ThongBao", b =>
                {
                    b.Navigation("DanhSachBinhLuan");
                });
#pragma warning restore 612, 618
        }
    }
}
